const estadosCatalogo = [
    { clave: "AGS", nombres: ["Aguascalientes"] },
    { clave: "BC", nombres: ["Baja California", "Baja California Norte"] },
    { clave: "BCS", nombres: ["Baja California Sur"] },
    { clave: "CAMP", nombres: ["Campeche"] },
    { clave: "CDMX", nombres: ["Ciudad de México", "CDMX", "Ciudad de Mexico"] },
    { clave: "COAH", nombres: ["Coahuila", "Coahuila de Zaragoza"] },
    { clave: "COL", nombres: ["Colima"] },
    { clave: "CHIS", nombres: ["Chiapas"] },
    { clave: "CHIH", nombres: ["Chihuahua"] },
    { clave: "DGO", nombres: ["Durango"] },
    { clave: "GTO", nombres: ["Guanajuato"] },
    { clave: "GRO", nombres: ["Guerrero"] },
    { clave: "HGO", nombres: ["Hidalgo"] },
    { clave: "JAL", nombres: ["Jalisco"] },
    { clave: "MEX", nombres: ["México", "Estado de México", "Edomex"] },
    { clave: "MICH", nombres: ["Michoacán", "Michoacan de Ocampo"] },
    { clave: "MOR", nombres: ["Morelos"] },
    { clave: "NAY", nombres: ["Nayarit"] },
    { clave: "NL", nombres: ["Nuevo León", "Nuevo Leon"] },
    { clave: "OAX", nombres: ["Oaxaca"] },
    { clave: "PUE", nombres: ["Puebla"] },
    { clave: "QRO", nombres: ["Querétaro", "Queretaro"] },
    { clave: "QROO", nombres: ["Quintana Roo"] },
    { clave: "SLP", nombres: ["San Luis Potosí", "San Luis Potosi"] },
    { clave: "SIN", nombres: ["Sinaloa"] },
    { clave: "SON", nombres: ["Sonora"] },
    { clave: "TAB", nombres: ["Tabasco"] },
    { clave: "TAMPS", nombres: ["Tamaulipas"] },
    { clave: "TLAX", nombres: ["Tlaxcala"] },
    { clave: "VER", nombres: ["Veracruz"] },
    { clave: "YUC", nombres: ["Yucatán", "Yucatan"] },
    { clave: "ZAC", nombres: ["Zacatecas"] }
];

module.exports = { estadosCatalogo };